/**
 * Constants for the Home page only.
 * Not imported by any other page — page-scoped content lives here,
 * cross-page content belongs in `@/shared/constants`.
 * Display text is translated — see the `home` namespace in messages/*.json;
 * this file only holds non-text data (image paths, ids, hrefs).
 */

// Hero section
export const heroContent = {
  mapImage: "/images/home/vn-map.png",
  /** Poster is the hero's first paint and therefore its LCP candidate —
   * the video itself is deliberately held back until after `load`. */
  videoPoster: "/images/home/hero-poster.webp",
  /**
   * Order is the selection order: the browser takes the first entry whose
   * `type` it can decode and whose `media` matches. AV1/WebM leads
   * because it is the smallest, the H.264/MP4 twin behind it is what
   * Safari (which needs hardware support for AV1) actually plays, and the
   * unqualified 1080 pair at the end is the catch-all for any browser
   * that ignores `media` on a `<source>`.
   *
   * Generated by `yarn videos:optimize` — keep in sync with its
   * RENDITIONS list.
   */
  videoSources: [
    {
      src: "/videos/home/hero-banner.720.webm",
      type: "video/webm",
      media: "(max-width: 767px)",
    },
    {
      src: "/videos/home/hero-banner.720.mp4",
      type: "video/mp4",
      media: "(max-width: 767px)",
    },
    { src: "/videos/home/hero-banner.1080.webm", type: "video/webm" },
    { src: "/videos/home/hero-banner.1080.mp4", type: "video/mp4" },
  ],
} as const;

// Trust badges (Hero section)
export const trustBadges = [
  { id: "tripadvisor-2023", image: "/images/home/trip-advisor.png" },
  { id: "tripadvisor-2024", image: "/images/home/trip-advisor.png" },
  { id: "tripadvisor-2025", image: "/images/home/trip-advisor.png" },
  { id: "restaurant-guru-2025", image: "/images/home/guru-recommend.png" },
] as const;

// Story section ("Chuyện Nhà kể")
export const storyContent = {
  backgroundImage: "/images/home/story/background.webp",
  backgroundImageMobile: "/images/home/story/background-mb.webp",
};

export const storyStates = [
  { id: "dsv", image: "/images/home/story/story-dsv.webp" },
  { id: "ht", image: "/images/home/story/story-ht.webp" },
  { id: "tt", image: "/images/home/story/story-tt.webp" },
] as const;

// Menu section
export const menuContent = {
  backgroundImage: "/images/home/menu/background.webp",
  backgroundImageMobile: "/images/home/menu/background-mb.webp",
};

/** How long each spread holds before the panel turns to the next one
 * within the same category. */
export const MENU_SPREAD_INTERVAL_MS = 2000;

/** Hover has to settle before it takes the panel over. Without the delay a
 * pointer travelling down the list on its way somewhere else would trigger
 * every category it crosses. Clicking bypasses it — an explicit choice
 * shouldn't wait. */
export const MENU_HOVER_DEBOUNCE_MS = 500;

// Selecting a category turns the right-hand panel to its first spread, then
// the panel keeps turning through the rest of that category's folder on a
// timer. `dac-san-viet` is ordered north → south to follow the regional
// narrative the section is about; the others follow their file numbering.
export const menuCategoryList = [
  {
    id: "dac-san-viet",
    href: "/menu#dac-san-viet",
    spreads: [
      { src: "/images/home/menu/dsv/bac.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/bac-1.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/TRUNG.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/TRUNG1.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/TRUNG2.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/TRUNG3.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/nam.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/nam-1.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/nam-2.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/nam-3.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/PQ.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/PQ1.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/PQ2.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/PQ4.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/dsv/menu-moi-03.webp", width: 582, height: 842 },
      { src: "/images/home/menu/dsv/menu-moi-05.webp", width: 582, height: 842 },
    ],
  },
  {
    id: "pizza-classic",
    href: "/menu#pizza-classic",
    spreads: [
      { src: "/images/home/menu/pizza/pizza-32.webp", width: 595, height: 842 },
      { src: "/images/home/menu/pizza/pizza-33.webp", width: 595, height: 842 },
      { src: "/images/home/menu/pizza/pizza-34.webp", width: 595, height: 842 },
      { src: "/images/home/menu/pizza/pizza-35.webp", width: 595, height: 842 },
      { src: "/images/home/menu/pizza/pizza-36.webp", width: 595, height: 842 },
      { src: "/images/home/menu/pizza/pizza-37.webp", width: 595, height: 842 },
    ],
  },
  {
    id: "salad-appertiza",
    href: "/menu#salad",
    spreads: [
      { src: "/images/home/menu/salad/salad-02.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/salad/salad-03.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/salad/salad-04.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/salad/salad-06.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/salad/salad-07.webp", width: 1241, height: 1754 },
    ],
  },
  {
    id: "pasta",
    href: "/menu#pasta",
    spreads: [
      { src: "/images/home/menu/pasta/pasta-bac.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/pasta/pasta-bac-2.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/pasta/pasta-PQ.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/pasta/salad-11.webp", width: 1241, height: 1754 },
      { src: "/images/home/menu/pasta/salad-14.webp", width: 1241, height: 1754 },
    ],
  },
] as const;

// Humans section ("Người Nhà")
export const humansContent = {
  backgroundImage: "/images/home/humans/background.webp",
  backgroundImageMobile: "/images/home/humans/background-mb.webp",
  images: [
    { id: "human-1", src: "/images/home/humans/human-1.webp" },
    { id: "human-2", src: "/images/home/humans/human-2.webp" },
  ],
} as const;

export const humansLinkList = [
  { id: "humans-of-the-home", href: "/humans" },
  { id: "career-path", href: "/humans#career-path" },
  { id: "nha-tim-nguoi", href: "/humans#nha-tim-nguoi" },
] as const;

// Location section
export const locationContent = {
  backgroundImage: "/images/home/location/background.webp",
  backgroundImageMobile: "/images/home/location/background-mb.webp",
};

/** How long each photo holds before the panel crossfades to the next one
 * within the same location. Slower than the menu panel's turn rate — this
 * is ambiance, not something the visitor is meant to read line by line. */
export const LOCATION_SPREAD_INTERVAL_MS = 3200;

/** Hover has to settle before it switches the active location — same idea
 * as the menu list's hover debounce: without the delay, a pointer just
 * passing through on its way elsewhere would trigger every item it
 * crosses. Clicking bypasses it — an explicit choice shouldn't wait. */
export const LOCATION_HOVER_DEBOUNCE_MS = 500;

// Selecting a location crossfades the right-hand panel to its first photo,
// then the panel keeps advancing through the rest of that location's
// folder on a timer. Order follows each folder's own file numbering.
export const locationStates = [
  {
    id: "phu-quoc",
    spreads: [
      { src: "/images/home/location/phu-quoc/SHIN8696.jpg", width: 1977, height: 1318 },
      { src: "/images/home/location/phu-quoc/SHIN8715.jpg", width: 2032, height: 1355 },
      { src: "/images/home/location/phu-quoc/SHIN8752.jpg", width: 2059, height: 1373 },
      { src: "/images/home/location/phu-quoc/SHIN8756.jpg", width: 1981, height: 1321 },
      { src: "/images/home/location/phu-quoc/SHIN8770.jpg", width: 2186, height: 3280 },
      { src: "/images/home/location/phu-quoc/SHIN8774.jpg", width: 6000, height: 4000 },
      { src: "/images/home/location/phu-quoc/SHIN8777.jpg", width: 4000, height: 6000 },
      { src: "/images/home/location/phu-quoc/SHIN8785.jpg", width: 6000, height: 4000 },
      { src: "/images/home/location/phu-quoc/SHIN8797.jpg", width: 6000, height: 4000 },
      { src: "/images/home/location/phu-quoc/SHIN8801.jpg", width: 6000, height: 4000 },
    ],
  },
  {
    id: "nha-trang",
    spreads: [
      { src: "/images/home/location/nha-trang/DSC03188.webp", width: 2000, height: 1334 },
      { src: "/images/home/location/nha-trang/DSC03364.webp", width: 2545, height: 1697 },
      { src: "/images/home/location/nha-trang/HUG02484.webp", width: 1319, height: 1978 },
      { src: "/images/home/location/nha-trang/HUG02507.webp", width: 1885, height: 1222 },
      { src: "/images/home/location/nha-trang/HUG02944.webp", width: 1271, height: 1861 },
      { src: "/images/home/location/nha-trang/TRG08978.webp", width: 1495, height: 2243 },
    ],
  },
] as const;
