/**
 * Constants for the Home page only.
 * Not imported by any other page — page-scoped content lives here,
 * cross-page content belongs in `@/shared/constants`.
 * Display text is translated — see the `home` namespace in messages/*.json;
 * this file only holds non-text data (image paths, ids, hrefs).
 */
import { locationPhotos } from "@/shared/constants/location-photos.constant";
import { menuSpreads } from "@/shared/constants/menu-spreads.constant";

// Hero section
export const heroContent = {
  mapImage: "/images/home/vn-map.png",
  /** Poster is the hero's first paint and therefore its LCP candidate —
   * the video itself is deliberately held back until after `load`. */
  videoPoster: "/images/home/hero-poster.webp",
  /**
   * Order is the selection order: the browser takes the first entry whose
   * `type` it can decode and whose `media` matches. AV1/WebM leads
   * because it is the smallest, the H.264/MP4 twin behind it is what
   * Safari (which needs hardware support for AV1) actually plays, and the
   * unqualified 1080 pair at the end is the catch-all for any browser
   * that ignores `media` on a `<source>`.
   *
   * Generated by `yarn videos:optimize` — keep in sync with its
   * RENDITIONS list.
   */
  videoSources: [
    {
      src: "/videos/home/hero-banner.720.webm",
      type: "video/webm",
      media: "(max-width: 767px)",
    },
    {
      src: "/videos/home/hero-banner.720.mp4",
      type: "video/mp4",
      media: "(max-width: 767px)",
    },
    { src: "/videos/home/hero-banner.1080.webm", type: "video/webm" },
    { src: "/videos/home/hero-banner.1080.mp4", type: "video/mp4" },
  ],
} as const;

// Trust badges (Hero section)
export const trustBadges = [
  { id: "tripadvisor-2023", image: "/images/home/trip-advisor.png" },
  { id: "tripadvisor-2024", image: "/images/home/trip-advisor.png" },
  { id: "tripadvisor-2025", image: "/images/home/trip-advisor.png" },
  { id: "restaurant-guru-2025", image: "/images/home/guru-recommend.png" },
] as const;

// Story section ("Chuyện Nhà kể")
export const storyContent = {
  backgroundImage: "/images/home/story/background.webp",
  backgroundImageMobile: "/images/home/story/background-mb.webp",
};

/** `href` is where the arrow in the photo's bottom-right corner leads —
 * each state is a teaser for the screen that tells that part of the story
 * in full. */
export const storyStates = [
  { id: "dsv", image: "/images/home/story/story-dsv.webp", href: "/menu" },
  { id: "ht", image: "/images/home/story/story-ht.webp", href: "/story" },
  { id: "tt", image: "/images/home/story/story-tt.webp", href: "/humans" },
] as const;

/** Hover has to settle before it takes the panel over. Without the delay a
 * pointer travelling down the list on its way somewhere else would trigger
 * every category it crosses. Clicking bypasses it — an explicit choice
 * shouldn't wait. */
export const MENU_HOVER_DEBOUNCE_MS = 500;

// Selecting a category turns the right-hand panel to its first spread, then
// the panel keeps turning through the rest of that category's folder on a
// timer. The artwork itself lives in `shared/constants/menu-spreads.constant.ts`
// — /menu's accordion opens the same sets, so neither screen owns them any
// more.
export const menuCategoryList = [
  { id: "dac-san-viet", spreads: menuSpreads["dac-san-viet"] },
  { id: "pizza-classic", spreads: menuSpreads["pizza-classic"] },
  { id: "salad-appertiza", spreads: menuSpreads.salad },
  { id: "pasta", spreads: menuSpreads.pasta },
] as const;

// Humans section ("Người Nhà")
export const humansContent = {
  backgroundImage: "/images/home/humans/background.webp",
  backgroundImageMobile: "/images/home/humans/background-mb.webp",
  images: [
    { id: "human-1", src: "/images/home/humans/human-1.webp" },
    { id: "human-2", src: "/images/home/humans/human-2.webp" },
  ],
} as const;

/** The same three destinations as /humans' own hero list, so a visitor
 * gets to the same place from either screen. "Career Path" is the blog
 * post that has not been chosen yet — see the note on
 * `humansHeroLinkList` in the /humans constants. */
export const humansLinkList = [
  { id: "humans-of-the-home", href: "/humans#humans-of-the-home" },
  { id: "career-path", href: "/story" },
  { id: "nha-tim-nguoi", href: "/humans#nha-tim-nguoi" },
] as const;

/** How long each photo holds before the panel crossfades to the next one
 * within the same location. Slower than the menu panel's turn rate — this
 * is ambiance, not something the visitor is meant to read line by line. */
export const LOCATION_SPREAD_INTERVAL_MS = 3200;

/** Hover has to settle before it switches the active location — same idea
 * as the menu list's hover debounce: without the delay, a pointer just
 * passing through on its way elsewhere would trigger every item it
 * crosses. Clicking bypasses it — an explicit choice shouldn't wait. */
export const LOCATION_HOVER_DEBOUNCE_MS = 500;

// Selecting a location crossfades the right-hand panel to its first photo,
// then the panel keeps advancing through the rest of that location's
// folder on a timer. The photos themselves live in
// `shared/constants/location-photos.constant.ts` — /space's filmstrip
// shows the same folders, so neither screen owns them any more. `id` is
// also the `/space#<id>` anchor this panel's CTA deep-links to.
export const locationStates = [
  { id: "phu-quoc", spreads: locationPhotos["phu-quoc"] },
  { id: "nha-trang", spreads: locationPhotos["nha-trang"] },
] as const;
