/**
 * Content for the /humans screen only.
 * Not imported by any other screen — page-scoped content lives here.
 * Display text is translated — see the `humansPage` namespace in
 * messages/*.json; this file only holds non-text data (image paths, ids, hrefs).
 */

import { businessInfo } from '@/shared/constants/site.constant';

// Hero section
export const humansHeroContent = {
  /** Poster is the hero's first paint and therefore its LCP candidate —
   * the video itself is held back until after `load`. */
  videoPoster: "/images/humans/hero-poster.webp",
  /**
   * The source footage was VP9-in-MP4, which Safari cannot play at all,
   * so this hero was rendering as an empty box on every Apple device.
   * The H.264 rendition is what fixes that; AV1 leads because it is
   * smaller wherever it decodes.
   *
   * Only 720-wide renditions exist — the source is 720 wide, so a larger
   * one would be an upscale. Generated by `yarn videos:optimize`.
   */
  videoSources: [
    { src: "/videos/humans/hero.720.webm", type: "video/webm" },
    { src: "/videos/humans/hero.720.mp4", type: "video/mp4" },
  ],
} as const;

/**
 * Hero link list.
 *
 * `anchor` entries jump to a section further down this page — the ids are
 * on the sections themselves, which carry a `scroll-mt` equal to the fixed
 * header so the heading is not left underneath the bar.
 *
 * "Career Path" is meant to open a specific blog post; that article has not
 * been chosen yet, so it points at the /story index in the meantime rather
 * than at a dead anchor. Swap the `href` for `/story/<slug>` when the piece
 * is picked.
 */
export const humansHeroLinkList = [
  { id: "humans-of-the-home", href: "#humans-of-the-home", kind: "anchor" },
  { id: "career-path", href: "/story", kind: "route" },
  { id: "nha-tim-nguoi", href: "#nha-tim-nguoi", kind: "anchor" },
] as const;

// Intro section — quote over a monstera texture panel
export const humansIntroContent = {
  backgroundImage: "/images/humans/bg-1.webp",
  backgroundImageMobile: "/images/humans/bg-1-mb.webp",
};

// Chef Nhà story — dark navy / gold split background
export const humansChefStoryContent = {
  image: {
    src: "/images/humans/chef.webp",
    mobileSrc: "/images/humans/chef-mb.webp",
  },
};

// Người Nhà story — mirrored linen / gold split background
export const humansPeopleStoryContent = {
  image: {
    src: "/images/humans/homer.webp",
    mobileSrc: "/images/humans/homer-mb.webp",
  },
};

// Values section — monstera texture panel, distinct from the intro's
export const humansValuesContent = {
  backgroundImage: "/images/humans/bg-3.webp",
  backgroundImageMobile: "/images/humans/bg-3-mb.webp",
};

// Values section — column order/pairing follows the Figma source exactly
export const humansValuesList = [
  { id: "ket-noi" },
  { id: "sang-tao" },
  { id: "tan-tam" },
] as const;

// CTA section — full-bleed photo, closes the page with the recruiting pitch.
// The button applies via email since no dedicated careers page exists yet.
export const humansCtaContent = {
  image: {
    src: "/images/humans/be-homer.webp",
    mobileSrc: "/images/humans/be-homer-mb.webp",
  },
  ctaHref: `mailto:${businessInfo.email}`,
};
