/**
 * Content for the /humans screen only.
 * Not imported by any other screen — page-scoped content lives here.
 * Display text is translated — see the `humansPage` namespace in
 * messages/*.json; this file only holds non-text data (image paths, ids, hrefs).
 */

import { businessInfo } from '@/shared/constants/site.constant';

// Hero section
export const humansHeroContent = {
  /** Poster is the hero's first paint and therefore its LCP candidate —
   * the video itself is held back until after `load`. */
  videoPoster: "/images/humans/hero-poster.webp",
  /**
   * The source footage is HEVC-in-MP4, which Chrome/Firefox/Android
   * generally cannot decode (licensing, not codec support), so this hero
   * was rendering as an empty box outside Safari. The H.264 rendition is
   * what fixes that; AV1 leads because it is smaller wherever it decodes.
   *
   * Order is the selection order, same as the home hero: the browser
   * takes the first entry whose `type` it can decode and whose `media`
   * matches. Generated by `yarn videos:optimize` — keep in sync with its
   * HUMANS_RENDITIONS list.
   *
   * The ladder is 1080/1920 rather than the home hero's 720/1080: this
   * is 16:9 footage in a full-viewport box, so `object-cover` upscales
   * it hard (~2.5x measured on a 1080 rendition at DPR 2) and the extra
   * pixels are what keep it sharp. The `media` gate is what pays for
   * them — phones never fetch the 1920 file, so the heavier rendition
   * only ever reaches the screens wide enough to show it.
   */
  videoSources: [
    {
      src: "/videos/humans/hero.1080.webm",
      type: "video/webm",
      media: "(max-width: 767px)",
    },
    {
      src: "/videos/humans/hero.1080.mp4",
      type: "video/mp4",
      media: "(max-width: 767px)",
    },
    { src: "/videos/humans/hero.1920.webm", type: "video/webm" },
    { src: "/videos/humans/hero.1920.mp4", type: "video/mp4" },
  ],
} as const;

/**
 * Hero link list.
 *
 * `anchor` entries jump to a section further down this page — the ids are
 * on the sections themselves, which carry a `scroll-mt` equal to the fixed
 * header so the heading is not left underneath the bar.
 *
 * "Career Path" is meant to open a specific blog post; that article has not
 * been chosen yet, so it points at the /story index in the meantime rather
 * than at a dead anchor. Swap the `href` for `/story/<slug>` when the piece
 * is picked.
 */
export const humansHeroLinkList = [
  { id: "humans-of-the-home", href: "#humans-of-the-home", kind: "anchor" },
  { id: "career-path", href: "/story/nha-tim-nguoi", kind: "route" },
  { id: "nha-tim-nguoi", href: "/story/nha-tim-nguoi", kind: "route" },
] as const;

// Intro section — quote over a monstera texture panel
export const humansIntroContent = {
  backgroundImage: "/images/humans/bg-1.webp",
  backgroundImageMobile: "/images/humans/bg-1-mb.webp",
};

// Chef Nhà story — dark navy / gold split background
export const humansChefStoryContent = {
  image: {
    src: "/images/humans/chef.webp",
    mobileSrc: "/images/humans/chef-mb.webp",
  },
};

// Người Nhà story — mirrored linen / gold split background
export const humansPeopleStoryContent = {
  image: {
    src: "/images/humans/homer.webp",
    mobileSrc: "/images/humans/homer-mb.webp",
  },
};

// Values section — monstera texture panel, distinct from the intro's
export const humansValuesContent = {
  backgroundImage: "/images/humans/bg-3.webp",
  backgroundImageMobile: "/images/humans/bg-3-mb.webp",
};

// Values section — column order/pairing follows the Figma source exactly
export const humansValuesList = [
  { id: "ket-noi" },
  { id: "sang-tao" },
  { id: "tan-tam" },
] as const;

// CTA section — full-bleed photo, closes the page with the recruiting pitch.
// The button applies via email since no dedicated careers page exists yet.
export const humansCtaContent = {
  image: {
    src: "/images/humans/be-homer.png",
    mobileSrc: "/images/humans/be-homer-mb.webp",
  },
  ctaHref: "/story/nha-tim-nguoi",
};
