/**
 * The dark dó paper texture shared by the /story-detail article, the home
 * menu and location panels, and the /humans chef-story band — one tile
 * rather than a separate crop of the same photograph per screen (the home
 * menu and location panels used to literally duplicate the same file byte
 * for byte).
 *
 * Unlike `CREAM_PAPER_TILE` below, this has no separate mobile crop: the
 * source (`pattern-bg.webp`) is high-resolution enough that one 300px tile
 * covers every breakpoint, so callers don't need a `lg:hidden`/`lg:block`
 * pair — one div, one `backgroundImage`, everywhere.
 *
 * Generated by `yarn images:tile` from `pattern-bg.webp` — see
 * `scripts/make-seamless-tile.mjs` for why it's a small cropped-and-blended
 * tile rather than the full photograph stretched across the section.
 */
export const DARK_PAPER_TILE = '/images/pattern-bg.webp';

/**
 * The CSS size the tile above is painted at — half its 300px pixel size, so
 * a `devicePixelRatio: 2` screen maps it 1:1 instead of upscaling it into a
 * blurry smear. Both axes get this value: the tile is square, and
 * `background-repeat` fills the section in x and y from it. Changing this
 * means changing `crop` for this job in `scripts/make-seamless-tile.mjs` to
 * keep the 2:1 ratio.
 */
export const DARK_PAPER_TILE_SIZE = '300px 300px';

/**
 * The cream paper texture shared by the /story-detail related band, the
 * /space signature backdrop, and the /story landing page header — one
 * asset, tiled with `background-repeat`, instead of three per-screen copies
 * of the same photograph.
 *
 * Generated by `yarn images:tile` from `background.webp`/`background-mb.webp`
 * — see `scripts/make-seamless-tile.mjs` for why it's a small cropped-and-
 * blended tile rather than the full photograph stretched across the section.
 */
export const CREAM_PAPER_TILE = {
  desktop: '/images/home/story/background-tile.webp',
  mobile: '/images/home/story/background-mb-tile.webp',
};

/**
 * The CSS size each tile above is painted at — half its real pixel size, so
 * a `devicePixelRatio: 2` screen maps it 1:1 instead of upscaling it into a
 * blurry smear (see `DARK_PAPER_TILE_SIZE` above for the full explanation;
 * this is the same technique applied to the cream texture's two tiles).
 * The mobile tile is smaller than the desktop one because its source photo
 * is only 430px wide, which caps how large a crop `make-seamless-tile.mjs`
 * can take from it.
 */
export const CREAM_PAPER_TILE_SIZE = {
  desktop: '200px 200px',
  mobile: '180px 180px',
};
